public class AutoGeneratedRollNumber {
    public static void main(String[] args){
        StaticStudent s1= new StaticStudent();
        System.out.println(s1.getStudentRollNo());
        StaticStudent s2= new StaticStudent();
        System.out.println(s2.getStudentRollNo());
        StaticStudent s3= new StaticStudent();
        System.out.println(s3.getStudentRollNo());
    }
}
class StaticStudent{
    private static int rollNo=0;

    public int getStudentRollNo() {
        return studentRollNo;
    }

    public void setStudentRollNo(int studentRollNo) {
        this.studentRollNo = studentRollNo;
    }

    int studentRollNo;
    public StaticStudent(){
        studentRollNo=++rollNo;
    }
}